### ISSUE TITLE
Move to StreetComplete?

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/sc-photo-service#11]
I created a github organization "StreetComplete". Could we move this repo into the organization?

**Comment by exploide** [comment]
Sure, let's do this. But I don't have permissions to move the repository over to `streetcomplete`.

**Comment by westnordost** [comment]
Weird, but you are the owner. Does it say whay you don't have permission?

**Comment by exploide** [comment]
Maybe I'm doing this plain wrong but when I go to "Settings" > "Transfer ownership" and enter "streetcomplete" as a target organisation, it tells me

> You don’t have the permission to create public repositories on streetcomplete 

So it looks more like a permission problem on the destination.

**Comment by westnordost** [comment]
Ah, so that's the problem

**Comment by exploide** [comment]
Thank you. Done :)
