### ISSUE TITLE
Filenames 

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/sc-photo-service#6]
I was reminded of a reason for having filenames not generated from a counting number: Even when directory listing is off, people could mass-download the pictures with a curl-for loop.
So, if there is a really good (security? privacy?) reason to disable directory listing, then this reason is also valid for not having filenames that count up.

What do you think?

**Comment by exploide** [comment]
> So, if there is a really good (security? privacy?) reason to disable directory listing, then this reason is also valid for not having filenames that count up.

That's true.

> What do you think?

The question is: Is there a privacy reason? I also thought of that when implementing the mechanism. But I got the opinion that all the pictures are linked publicly on OSM anyway and I don't know why it could be a problem when someone downloads and views them all.

There are also Mapillary and OpenStreetCam, which make huge amounts of pictures taken during survey publicly accessible.

**Comment by westnordost** [comment]
Soon (GDPR), notes will not be visible publicly anymore. (But well, to create an account at OSM is enough to make it visible again.)

**Comment by westnordost** [comment]
Well, I guess it requires about the same amount of bad intent to create an OSM account to download notes data with the plan to not respecting the GDPR than to blindly curl-loop a directory of images.

**Comment by exploide** [comment]
Yes, and then you can even download the planet dump containing notes and systematically extract all URLs.

And even if not. What would be a countermeasure? Randomized filenames would need to be comparably long to avoid brute forcing. But originally we wanted the filenames to be as short as possible.
