### ISSUE TITLE
StreetComplete-relation

### ISSUE THREAD

**Issue by rugk** [streetcomplete/sc-photo-service#7]
Maybe this should be added to https://github.com/westnordost/StreetComplete/blob/master/CONTRIBUTING.md#streetcomplete-related-projects?

Also consider adding the "StreetComplete" tag here. :smile:

**Comment by exploide** [comment]
> Also consider adding the "StreetComplete" tag here. 

Done.

Adding this to `CONTRIBUTING.md` of StreetComplete is rather an issue there. You seem to maintain this list. Would to submit a PR there?

**Comment by rugk** [comment]
I dont maintain it :smile: Just created it, so better do a PR there. :smile:

**Comment by exploide** [comment]
Ok, did it. https://github.com/westnordost/StreetComplete/pull/1196
