### ISSUE TITLE
Delete photos of closed OSM notes

### ISSUE THREAD

**Issue by rugk** [streetcomplete/sc-photo-service#9]
I did not check whether it is already implemented, but possibly you can have some mechanism to clean-up old photos. (also to save space and so on…)

So:
* if a note to a photo has been closed for, say, 3 months
* and if the photo is older than 12 months or so

…then we can likely delete it.

Maybe this is an idea?

**Comment by exploide** [comment]
This logic is already implemented in [cleanup.php](https://github.com/exploide/sc-photo-service/blob/master/cleanup.php) and can be configured in [config.php](https://github.com/exploide/sc-photo-service/blob/master/config.sample.php).

By default, the photo is deleted seven days after the note was closed. Additionally, the cron job starts deleting the oldest photos when the configured directory size is exceeded.

It may be the case that other parameters are set in production.

Have you got the impression that this does not work as expected?

**Comment by rugk** [comment]
Np, don't use it, just looked through the Readme.
